version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: studentsdb
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-students_db}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
            MYSQL_USER: ${DB_USERNAME:-laravel_user}
            MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - "9999:3306"
        networks:
            - students_network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

    redis:
        image: redis:latest
        container_name: students_redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - students_network
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

#    app:
#        build:
#            context: .
#            dockerfile: Dockerfile
#        container_name: laravel_app
#        restart: unless-stopped
#        working_dir: /var/www/html
#        volumes:
#            - ./storage/app:/var/www/html/storage/app
#            - ./storage/logs:/var/www/html/storage/logs
#        ports:
#            - "8000:80"
#        environment:
#            - DB_HOST=mysql
#            - DB_PORT=3306
#            - DB_DATABASE=${DB_DATABASE:-laravel}
#            - DB_USERNAME=${DB_USERNAME:-laravel_user}
#            - DB_PASSWORD=${DB_PASSWORD:-secret}
#            - REDIS_HOST=redis
#            - REDIS_PORT=6379
#            - REDIS_PASSWORD=null
#        depends_on:
#            mysql:
#                condition: service_healthy
#            redis:
#                condition: service_healthy
#        networks:
#            - students_network

networks:
    students_network:
        driver: bridge

volumes:
    mysql_data:
        driver: local
    redis_data:
        driver: local
